apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: srikart-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: YOUR_DOCKERHUB_USERNAME/srikart-discovery-server:latest
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: srikart-production
spec:
  selector:
    app: discovery-server
  ports:
  - port: 8761
    targetPort: 8761
  type: ClusterIP
