apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: srikart-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: srikarcool1/frontend:latest
        ports:
        - containerPort: 8090
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: srikart-production
spec:
  selector:
    app: frontend-service
  ports:
  - port: 80
    targetPort: 8090
  type: LoadBalancer
