apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: srikart-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: YOUR_DOCKERHUB_USERNAME/srikart-inventory-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: srikart-production
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
