apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: srikart-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: <+artifact.image>
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: srikart-config
              key: eureka-url
        - name: SERVER_PORT
          value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: srikart-production
spec:
  selector:
    app: order-service
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  type: ClusterIP
