apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: srikart-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: <+artifact.image>
        ports:
        - containerPort: 8083
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: srikart-config
              key: eureka-url
        - name: SERVER_PORT
          value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: srikart-production
spec:
  selector:
    app: payment-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
