apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: srikart-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: <+artifact.image>
        ports:
        - containerPort: 8084
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: srikart-config
              key: eureka-url
        - name: SERVER_PORT
          value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: srikart-production
spec:
  selector:
    app: user-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  type: ClusterIP
